name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6
      - name: Install kcov
        run: |
          sudo apt update
          sudo apt install kcov -y
      - name: Set up zig
        uses: mlugg/setup-zig@v2
        with:
          version: master
      - name: Run zig fmt
        run: zig fmt --check .
      - name: Build
        run: zig build
      - name: Run test with kcov
        run: |
          kcov --version
          zig build test -Dtest-coverage=true --summary all
      - name: Upload coverage
        uses: codecov/codecov-action@v7
        with:
          directory: ./kcov-output
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          fail_ci_if_error: true
